services:
  postgres:
    image: postgres:16-alpine
    container_name: guild_planner_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: guild_planner
      POSTGRES_PASSWORD: guild_planner_secret
      POSTGRES_DB: guild_planner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
